import {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  BellRing,
  BookCheck,
  BookMarked,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  CheckCircle2,
  CircleGauge,
  ClipboardList,
  Copy,
  CreditCard,
  FileBarChart,
  FileClock,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Gauge,
  GitBranch,
  GitMerge,
  GitPullRequestArrow,
  Handshake,
  Inbox,
  KeyRound,
  Landmark,
  Laptop,
  LayoutDashboard,
  ListChecks,
  Lock,
  Map as MapIcon,
  MessageSquareText,
  MessagesSquare,
  Percent,
  Presentation,
  Receipt,
  Scale,
  ScanLine,
  Send,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  SplitSquareHorizontal,
  Target,
  Users,
  Users2,
  UserCheck,
  UserMinus,
  Wallet,
  Waves,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/**
 * Server components can't hand an icon *component* to a client component, so
 * icon-bearing page data references icons by name and they are resolved here.
 * Add a name here when a page needs a new one.
 */
export const LUCIDE: Record<string, LucideIcon> = {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  BellRing,
  BookCheck,
  BookMarked,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  CheckCircle2,
  CircleGauge,
  GaugeCircle: CircleGauge,
  ClipboardList,
  Copy,
  CreditCard,
  FileBarChart,
  FileClock,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Gauge,
  GitBranch,
  GitMerge,
  GitPullRequestArrow,
  Handshake,
  Inbox,
  KeyRound,
  Landmark,
  Laptop,
  LayoutDashboard,
  ListChecks,
  Lock,
  Map: MapIcon,
  MessageSquareText,
  MessagesSquare,
  Percent,
  Presentation,
  Receipt,
  Scale,
  ScanLine,
  Send,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  SplitSquareHorizontal,
  Target,
  Users,
  Users2,
  UserCheck,
  UserMinus,
  Wallet,
  Waves,
  Workflow,
  Wrench,
};

export type LucideName = keyof typeof LUCIDE;
